on: push
name: golang
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: run
      uses: cedrickring/golang-action@1.6.0
    - name: Go Modules
      uses: cedrickring/golang-action@1.6.0
       env:
          GO111MODULE: "on"
